services:
  backend:
    build:
      context: ./SmartJourney.API
      dockerfile: Dockerfile
    ports:
      - "5110:8080"
    volumes:
      - sqlite_data:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./smart-journey-ui
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
